// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_lecoinoccasion.dart';
/// // ...
/// await firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI7Z-Llt6OpiuySUeNi9ce_tvhN8_GLz8',
    appId: '1:902171315942:web:71ea3b1b4ee85f66fc3527',
    messagingSenderId: '902171315942',
    projectId: 'lecoinoccasion',
    authDomain: 'lecoinoccasion.firebaseapp.com',
    storageBucket: 'lecoinoccasion.appspot.com',
    measurementId: 'G-QZR8KTP1BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuBn34kCSbCXHmzH_JDDMZzig5d1DUk4g',
    appId: '1:902171315942:android:7adf69c4d5ff4f42fc3527',
    messagingSenderId: '902171315942',
    projectId: 'lecoinoccasion',
    storageBucket: 'lecoinoccasion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChFW9mCg1M71NgyxxYAdtFionWv2HsquE',
    appId: '1:902171315942:ios:bd6faf4ef1a06c36fc3527',
    messagingSenderId: '902171315942',
    projectId: 'lecoinoccasion',
    storageBucket: 'lecoinoccasion.appspot.com',
    iosClientId: '902171315942-g7c4nah1p67gsg0losh4fc7skc841620.apps.googleusercontent.com',
    iosBundleId: 'com.skonsoft.lecoinoccasion.fr',
  );
}
