// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_afariat.dart';
/// // ...
/// await firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVJ3lXoYG959xRw4-aiQ94Vt3gonQC44Q',
    appId: '1:346620136541:web:54d8dacca9dc0e2a37d1b4',
    messagingSenderId: '346620136541',
    projectId: 'afariat',
    authDomain: 'afariat.firebaseapp.com',
    storageBucket: 'afariat.appspot.com',
    measurementId: 'G-6M78MJ3RLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw-mpg1Ms_2JizQCtHEKcomS1--KilJSI',
    appId: '1:346620136541:android:9cdedac924bad88a37d1b4',
    messagingSenderId: '346620136541',
    projectId: 'afariat',
    storageBucket: 'afariat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCENexT8X5tb80_FXMIq7OcRCHehn8bpxA',
    appId: '1:346620136541:ios:a907385b1e35711537d1b4',
    messagingSenderId: '346620136541',
    projectId: 'afariat',
    storageBucket: 'afariat.appspot.com',
    iosClientId: '346620136541-4dft5o4ienkra9rdc8691moidnvmb760.apps.googleusercontent.com',
    iosBundleId: 'com.skonsoft.afariat.com',
  );
}
