// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_lecoinoccasion.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKEny9wIvhrqOUn37NjLOxgFp2tOCBopM',
    appId: '1:37182458127:web:9227e02d06b7b4365cd67a',
    messagingSenderId: '37182458127',
    projectId: 'lecoinoccasion-3d60e',
    authDomain: 'lecoinoccasion-3d60e.firebaseapp.com',
    storageBucket: 'lecoinoccasion-3d60e.appspot.com',
    measurementId: 'G-XP3597ET4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ_lotjvBEBkfLKEkIGUN6ApDrmG7WHC8',
    appId: '1:37182458127:android:ff9b239ab673fac45cd67a',
    messagingSenderId: '37182458127',
    projectId: 'lecoinoccasion-3d60e',
    storageBucket: 'lecoinoccasion-3d60e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF1x9j6qsKO5kQQyF1_ZW_rYAqe5jRGQc',
    appId: '1:37182458127:ios:2c4ff32e2612130e5cd67a',
    messagingSenderId: '37182458127',
    projectId: 'lecoinoccasion-3d60e',
    storageBucket: 'lecoinoccasion-3d60e.appspot.com',
    iosClientId: '37182458127-s0t5ce6itskijhdtrgggjnn5m78mts9f.apps.googleusercontent.com',
    iosBundleId: 'com.skonsoft.lecoinoccasion.fr',
  );
}
